CONNECT mon_user/mon_mdp@XEPDB1
-- 04_create_procedures.sql
-- Procédures stockées

-- Table pour l'historique des salaires
CREATE TABLE salary_history (
    history_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       NUMBER,
    old_salary   NUMBER,
    new_salary   NUMBER,
    change_date  DATE,
    change_percent NUMBER,
    CONSTRAINT fk_hist_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);

-- Procédure pour augmenter le salaire d'un employé
CREATE OR REPLACE PROCEDURE increase_salary(
    p_emp_id  IN employees.emp_id%TYPE,
    p_percent IN NUMBER
) AS
    v_old_salary  employees.salary%TYPE;
    v_new_salary  employees.salary%TYPE;
    v_dept_name   departments.dept_name%TYPE;
BEGIN
    SELECT e.salary, d.dept_name
    INTO   v_old_salary, v_dept_name
    FROM   employees e
    LEFT JOIN departments d ON e.dept_id = d.dept_id
    WHERE  e.emp_id = p_emp_id;

    v_new_salary := v_old_salary * (1 + p_percent / 100);

    UPDATE employees SET salary = v_new_salary WHERE emp_id = p_emp_id;

    INSERT INTO salary_history (emp_id, old_salary, new_salary, change_date, change_percent)
    VALUES (p_emp_id, v_old_salary, v_new_salary, SYSDATE, p_percent);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✅ Augmentation de ' || p_percent || '% appliquée (' || v_dept_name || ')');
    DBMS_OUTPUT.PUT_LINE('   Salaire: ' || v_old_salary || ' → ' || v_new_salary);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('❌ Employé ' || p_emp_id || ' non trouvé');
        ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ Erreur: ' || SQLERRM);
        ROLLBACK;
END increase_salary;
/

-- Procédure pour assigner un employé à un projet
CREATE OR REPLACE PROCEDURE assign_to_project(
    p_emp_id     IN NUMBER,
    p_project_id IN NUMBER,
    p_role       IN VARCHAR2,
    p_hours      IN NUMBER
) AS
    v_emp_exists     NUMBER;
    v_project_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_emp_exists     FROM employees WHERE emp_id     = p_emp_id;
    SELECT COUNT(*) INTO v_project_exists FROM projects  WHERE project_id = p_project_id;

    IF v_emp_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Employé non trouvé');
    END IF;
    IF v_project_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Projet non trouvé');
    END IF;

    INSERT INTO employee_projects (emp_id, project_id, role, hours_allocated, assignment_date)
    VALUES (p_emp_id, p_project_id, p_role, p_hours, SYSDATE);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✅ Employé ' || p_emp_id || ' assigné au projet ' || p_project_id);

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('⚠️  Employé déjà assigné à ce projet');
        ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ Erreur: ' || SQLERRM);
        ROLLBACK;
END assign_to_project;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('✅ Procédures créées avec succès');
END;
/
