CONNECT mon_user/mon_mdp@XEPDB1
-- 07_create_triggers.sql
-- Triggers pour la validation et l'audit

-- Table d'audit des employés
CREATE TABLE employee_audit (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER,
    action_type   VARCHAR2(10),
    old_data      CLOB,
    new_data      CLOB,
    modified_by   VARCHAR2(30),
    modified_date DATE
);

-- Trigger : validation des salaires
CREATE OR REPLACE TRIGGER trg_check_salary
    BEFORE INSERT OR UPDATE OF salary ON employees
    FOR EACH ROW
BEGIN
    IF :NEW.salary > 100000 THEN
        RAISE_APPLICATION_ERROR(-20020, 'Salaire trop élevé (max 100,000)');
    ELSIF :NEW.salary < 10000 THEN
        RAISE_APPLICATION_ERROR(-20021, 'Salaire trop bas (min 10,000)');
    END IF;
END;
/

-- Trigger : audit des modifications d'employés
CREATE OR REPLACE TRIGGER trg_audit_employees
    AFTER INSERT OR UPDATE OR DELETE ON employees
    FOR EACH ROW
DECLARE
    v_action   VARCHAR2(10);
    v_old_data CLOB;
    v_new_data CLOB;
BEGIN
    IF INSERTING THEN
        v_action   := 'INSERT';
        v_new_data := 'ID:'  || :NEW.emp_id ||
                      '|Name:'  || :NEW.first_name || ' ' || :NEW.last_name ||
                      '|Email:' || :NEW.email ||
                      '|Salary:'|| :NEW.salary;
    ELSIF UPDATING THEN
        v_action   := 'UPDATE';
        v_old_data := 'ID:'  || :OLD.emp_id ||
                      '|Name:'  || :OLD.first_name || ' ' || :OLD.last_name ||
                      '|Email:' || :OLD.email ||
                      '|Salary:'|| :OLD.salary;
        v_new_data := 'ID:'  || :NEW.emp_id ||
                      '|Name:'  || :NEW.first_name || ' ' || :NEW.last_name ||
                      '|Email:' || :NEW.email ||
                      '|Salary:'|| :NEW.salary;
    ELSIF DELETING THEN
        v_action   := 'DELETE';
        v_old_data := 'ID:'  || :OLD.emp_id ||
                      '|Name:'  || :OLD.first_name || ' ' || :OLD.last_name ||
                      '|Email:' || :OLD.email ||
                      '|Salary:'|| :OLD.salary;
    END IF;

    INSERT INTO employee_audit
        (emp_id, action_type, old_data, new_data, modified_by, modified_date)
    VALUES
        (COALESCE(:NEW.emp_id, :OLD.emp_id),
         v_action, v_old_data, v_new_data, USER, SYSDATE);
END;
/

-- Trigger : mise à jour automatique du statut de projet
CREATE OR REPLACE TRIGGER trg_update_project_status
    BEFORE UPDATE OF end_date ON projects
    FOR EACH ROW
BEGIN
    IF :NEW.end_date < SYSDATE THEN
        :NEW.status := 'COMPLETED';
    END IF;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('✅ Triggers créés avec succès');
END;
/
